name: Deploy Astro Website to Draft S3

on:
   push:
      branches:
         - main

env:
   AWS_REGION : "us-east-1"

jobs:
   deploy:
      runs-on: ubuntu-latest
      permissions:
         id-token: write
         contents: read
      steps:
         - name: Checkout
           uses: actions/checkout@v4
         - name: Configure AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
              role-to-assume: ${{ secrets.ROLE }}
              role-session-name: ${{ secrets.ROLE_SESSION }}
              aws-region: ${{ env.AWS_REGION }}
         - name: Install modules
           run: npm ci
         - name: Build application
           run: npm run build
         - name: Deploy to S3
           run: aws s3 sync --delete ./dist/ s3://${{ secrets.PROD_BUCKET_NAME }}
         - name: Create CloudFront invalidation
           run: aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
